id: P1225EE31
initial_creation_type: input
source_metadata:
  title: Tri Songdetsen Series
  language: bo
  description: 'Texts by and about the Tibetan monarch Tri Songdetsen (khri srong
    lde btsan, 742–c.800), who played a major role in the establishment of Buddhism
    in Tibet:'
  volume:
    89943980c99a4cf99141b8163220b6bd:
      title: 'Snowy Lands: Praises to the Great Dharma Emperor Tri Songdetsen'
      parent: Praise
    fd13c531e48d43d68a821bf7c42ad3c9:
      title: 'Great Drum of the Devas: A Prayer to the Dharma King Tri Songdetsen'
      parent: Prayers
created_at: '2022-03-01T01:49:36.850771'
last_modified_at: '2022-03-01T01:49:36.850773'
